// Populates the database with test users and sample files.
// Run: node src/seed.js (or npm run seed)
// Safe to re-run - uses ON CONFLICT DO NOTHING.

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pool } from './db.js';
import { hashPassword } from './utils/hash.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');
const uploadsDir = join(projectRoot, 'uploads');

// ---- Run the migration ----
async function migrate() {
  const sql = readFileSync(join(projectRoot, 'migrations', '001_init.sql'), 'utf8');
  await pool.query(sql);
  console.log('Migration applied.');
}

// ---- Create a sample file on disk ----
function createSampleFile(subdir, fileName, mimeType) {
  const dir = join(uploadsDir, subdir);
  mkdirSync(dir, { recursive: true });
  const filePath = join(dir, fileName);

  // Generate realistic-looking content for each file type.  Text files
  // get readable prose, PDFs get actual rendered text (not a blank page),
  // and everything else gets a descriptive placeholder.
  let content;
  switch (mimeType) {
    case 'text/plain':
      content = [
        `=== ${fileName} ===`,
        `Created: ${new Date().toISOString().slice(0, 10)}`,
        '',
        'This file was generated by the seed script as sample data for the',
        'Secure Login System project.  Each user has their own set of files',
        'that only they can access - attempting to download another user\'s',
        'file returns HTTP 403.',
        '',
        'The download endpoint streams the raw bytes from disk and sets the',
        'Content-Disposition header so the browser triggers a save dialog.',
        '',
        '-- end of file --',
        '',
      ].join('\n');
      break;
    case 'application/pdf': {
      // Minimal but non-blank PDF - renders one line of visible text.
      // Uses a Type1 font (Helvetica) that every PDF viewer ships with.
      const line = `Sample PDF: ${fileName}`;
      const stream = `BT /F1 14 Tf 72 720 Td (${line}) Tj ET`;
      const streamLen = stream.length;
      content = [
        '%PDF-1.4',
        '1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj',
        '2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj',
        `3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Contents 4 0 R/Resources<</Font<</F1<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>>>>>>>endobj`,
        `4 0 obj<</Length ${streamLen}>>stream`,
        stream,
        'endstream endobj',
        'xref', '0 5',
        '0000000000 65535 f ',
        '0000000009 00000 n ',
        '0000000058 00000 n ',
        '0000000115 00000 n ',
        '0000000306 00000 n ',
        'trailer<</Size 5/Root 1 0 R>>',
        'startxref', '450',
        '%%EOF',
      ].join('\n');
      break;
    }
    default:
      // Images, docx, etc. - binary formats can't be faked convincingly
      // without a library, so we write a text description.  The mime type
      // and size in the database are still correct per seed-data.json.
      content = [
        `[${fileName}]`,
        `Type: ${mimeType}`,
        `Owner: ${subdir}`,
        '',
        'This is a placeholder generated by the seed script.',
        'In a production system this would be the actual binary content',
        `of the ${fileName.split('.').pop().toUpperCase()} file.`,
        '',
      ].join('\n');
  }

  writeFileSync(filePath, content);
  return `${subdir}/${fileName}`; // relative path stored in DB
}

// ---- Seed users and files ----
async function seed() {
  const raw = readFileSync(join(projectRoot, '..', 'seed-data.json'), 'utf8');
  const data = JSON.parse(raw);

  for (const u of data.users) {
    const hash = await hashPassword(u.password);

    await pool.query(
      `INSERT INTO users (id, email, password_hash, full_name, display_name, bio, role, created_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
       ON CONFLICT (id) DO NOTHING`,
      [
        u.id, u.email, hash,
        u.profile.fullName, u.profile.displayName,
        u.profile.bio, u.profile.role, u.profile.createdAt,
      ]
    );
    console.log(`  User: ${u.email} (${u.id})`);

    for (const f of u.files) {
      const diskPath = createSampleFile(u.id, f.fileName, f.mimeType);
      await pool.query(
        `INSERT INTO files (id, owner_id, file_name, mime_type, size_bytes, disk_path, uploaded_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         ON CONFLICT (id) DO NOTHING`,
        [f.id, f.ownerId, f.fileName, f.mimeType, f.sizeBytes, diskPath, f.uploadedAt]
      );
      console.log(`    File: ${f.fileName} (${f.id})`);
    }
  }
}

// ---- Main ----
async function main() {
  const migrateOnly = process.argv.includes('--migrate-only');

  try {
    await migrate();
    if (!migrateOnly) {
      await seed();
      console.log('\nDone. 3 users seeded, each with 2 files.');
      console.log('Credentials (all use the same password from seed-data.json):');
      console.log('  alice@example.com / Password123!');
      console.log('  bob@example.com   / Password123!');
      console.log('  carol@example.com / Password123!');
    }
  } catch (err) {
    console.error('Seed failed:', err);
    process.exitCode = 1;
  } finally {
    await pool.end();
  }
}

main();
